stages:
  - build
  - test

image: bitnami/java:11

Build Java Project:
  stage: build
  before_script:
    - apt update
    - apt install maven -y
  script:
    - mvn clean package
  artifacts:
    paths:
      - ./L02_1-ArrayList/target/L02_1-ArrayList-jar-with-dependencies.jar
      - ./LO6-Anatation/target/LO6-Anatation-jar-with-dependencies.jar

  tags:
    - default

Test Home Work 2 - DIY ArrayList:
  stage: test
  script:
    - ls
    - ls L02_1-ArrayList
    - ls ./L02_1-ArrayList/target/
    - java -jar ./L02_1-ArrayList/target/L02_1-ArrayList-jar-with-dependencies.jar
  dependencies:
    - Build Java Project
  when: manual
  tags:
    - default

Test Home Work 3 - Anatation:
  stage: test
  script:
    - java -jar ./LO6-Anatation/target/LO6-Anatation-jar-with-dependencies.jar
  dependencies:
    - Build Java Project
  when: manual
  tags:
    - default
