stages:
  - build
  - test

image: bitnami/java

Build Java Project:
  stage: build
  before_script:
    - apt update
    - apt install maven -y
  script:
    - mvn clean package
  tags:
    - default

Test Home Work 3 - Anatation:
  stage: test
  script:
    - java jar LO6-Anatation/target/LO6-Anatation-2019-04-27-SNAPSHOT.jar
  dependencies:
    - Build Java Project
  tags:
    - default
