version: 2
jobs:
    build:
      docker:
        - image: java
      steps:
        - checkout
        - run:
            name: Build Java Project
            command: 'mvn clean package'
    test:
      docker:
        - image: java
      steps:
        - checkout
        - run:
            name: Test Build
            command: java -jar LO6-Anatation/target/LO6-Anatation-2019-04-27-SNAPSHOT.jar
        - run:
            name: Generate code coverage
            command: './node_modules/.bin/nyc report --reporter=text-lcov'
        - store_artifacts:
            path: test-results.xml
            prefix: tests
        - store_artifacts:
            path: LO6-Anatation/target/LO6-Anatation-2019-04-27-SNAPSHOT.jar


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
